### PR TITLE
Added 3 plugins.

### PR DESCRIPTION
**Pull request by oddbear**
Added some plugins.

### CODE REVIEW

**Review by XeroxDev — CHANGES_REQUESTED** [review]
I've seen in your files the numeric order isn't right from the titles (you skipped the 2. So it's 1, 3, 4,...). Could you fix this before we merge it?

**Comment by oddbear** [comment]
Fixed

**Review by XeroxDev — CHANGES_REQUESTED** [review]
Multiple files have a wrong path / are duplicated.

**Comment by oddbear** [comment]
> Two files has a wrong path / are duplicated (keylight plugin and volumecontrol plugin)

Sorry, long day.
I see what happened.
I moved them, then I fixed the numbering issue in the open editor, and saved it... to the old path. 🤦‍♂️

**Review by XeroxDev — APPROVED** [review]
No problem. Now everything looks fine. Should be online with the next update schedule / cron.

**Comment by Tadgue** [comment]
So i've been trying to install a stupid plugin on my loupedeck using the SKF plugin and nothing i do seems to work. If anyone could help me out that would be greatly appreciated

**Comment by XeroxDev** [comment]
> So i've been trying to install a stupid plugin on my loupedeck using the SKF plugin and nothing i do seems to work. If anyone could help me out that would be greatly appreciated

To install a Loupedeck plugin you have multiple ways to do so. (Depending on what the Developer has created).
1. Easiest: If the developer created a installer file (.lplug4), you just have to double click it.
2. If you just have the .dll files, you have to move them into ``%LocalAppData%\Loupedeck\Plugins``. You can also create a new folder in ``%LocalAppData%\Loupedeck\Plugins`` with the plugin name and move it into that one (better structure)

**Pull request merged**
