### PR TITLE
Safari Web Browser Profile

### PR DESCRIPTION
**Pull request by durul**

### CODE REVIEW

**Review by XeroxDev — CHANGES_REQUESTED** [review]
Is this pr still WIP? Because your files are empty.

Also about the "lp4" file. I'm not 100% happy about hosting third party binary files, do you have a own place to host it? And shouldn't it be a "lplug4" file (See https://github.com/Loupedeck/LoupedeckPluginSdk4/wiki/Installing-And-Uninstalling-Plugins#using-installer-tool)

**Comment by durul** [comment]
> Is this pr still WIP? Because your files are empty.
> 
> Also about the "lp4" file. I'm not 100% happy about hosting third party binary files, do you have a own place to host it? And shouldn't it be a "lplug4" file (See https://github.com/Loupedeck/LoupedeckPluginSdk4/wiki/Installing-And-Uninstalling-Plugins#using-installer-tool)

Hello, this is not a plugin. This Lp4 is an Application Profile.

**Comment by XeroxDev** [comment]
> > Is this pr still WIP? Because your files are empty.
> > Also about the "lp4" file. I'm not 100% happy about hosting third party binary files, do you have a own place to host it? And shouldn't it be a "lplug4" file (See https://github.com/Loupedeck/LoupedeckPluginSdk4/wiki/Installing-And-Uninstalling-Plugins#using-installer-tool)
> 
> Hello, this is not a plugin. This Lp4 is an Application Profile.

Oh. Good to know. But you still should add a description, maybe a few screenshots and so on to the `home.md`

**Comment by durul** [comment]
> > > Is this pr still WIP? Because your files are empty.
> > > Also about the "lp4" file. I'm not 100% happy about hosting third party binary files, do you have a own place to host it? And shouldn't it be a "lplug4" file (See https://github.com/Loupedeck/LoupedeckPluginSdk4/wiki/Installing-And-Uninstalling-Plugins#using-installer-tool)
> > 
> > 
> > Hello, this is not a plugin. This Lp4 is an Application Profile.
> 
> Oh. Good to know. But you still should add a description, maybe a few screenshots and so on to the `home.md`

Hello Again, 

I updated home.md and screenshots are below. 


Screen Shot 2022-02-13 at 4 05 38 PM




Screen Shot 2022-02-13 at 4 05 27 PM

**Review by XeroxDev — CHANGES_REQUESTED** [review]
Small update in case you missed / forgot it. But like I said above, you should upload the binary / lp4 file somewhere else and add a download button in the home.md file. If you've done this and deleted the lp4 file from the PR, I can merge it.

**Pull request closed without merging**
